FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_ADMIN_SERVICE_URL=https://comfortmeng.com
ARG VITE_AUTH_SERVICE_URL=https://comfortmeng.com
ARG VITE_USER_SERVICE_URL=https://comfortmeng.com
ARG VITE_DRIVER_SERVICE_URL=https://comfortmeng.com
ARG VITE_BUS_SERVICE_URL=https://comfortmeng.com
ARG VITE_BOOKING_SERVICE_URL=https://comfortmeng.com
ARG VITE_PAYMENT_GATEWAY_URL=https://comfortmeng.com
ARG VITE_PAYMENT_HUB_URL=https://comfortmeng.com
ARG VITE_WALLET_SERVICE_URL=https://comfortmeng.com
ARG VITE_NOTIFICATION_SERVICE_URL=https://comfortmeng.com
ARG VITE_REWARD_SERVICE_URL=https://comfortmeng.com
ARG VITE_TERMS_SERVICE_URL=https://comfortmeng.com
ENV VITE_ADMIN_SERVICE_URL=$VITE_ADMIN_SERVICE_URL \
    VITE_AUTH_SERVICE_URL=$VITE_AUTH_SERVICE_URL \
    VITE_USER_SERVICE_URL=$VITE_USER_SERVICE_URL \
    VITE_DRIVER_SERVICE_URL=$VITE_DRIVER_SERVICE_URL \
    VITE_BUS_SERVICE_URL=$VITE_BUS_SERVICE_URL \
    VITE_BOOKING_SERVICE_URL=$VITE_BOOKING_SERVICE_URL \
    VITE_PAYMENT_GATEWAY_URL=$VITE_PAYMENT_GATEWAY_URL \
    VITE_PAYMENT_HUB_URL=$VITE_PAYMENT_HUB_URL \
    VITE_WALLET_SERVICE_URL=$VITE_WALLET_SERVICE_URL \
    VITE_NOTIFICATION_SERVICE_URL=$VITE_NOTIFICATION_SERVICE_URL \
    VITE_REWARD_SERVICE_URL=$VITE_REWARD_SERVICE_URL \
    VITE_TERMS_SERVICE_URL=$VITE_TERMS_SERVICE_URL
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
